### ISSUE TITLE
Fatal error on start in v5.3.0.0

### ISSUE THREAD

**Issue by sonst-was** [TransposonY/GestureSign#17]
Hi,

after noticing that my installed GestureSign (v.3.3.something) didn't work anymore (may have to do with Windows Updates I installed yesterday) I thought that it might be a good idea to look for a new version. So I found and installed the version you uploaded a few days ago (v.5.3). After the installation went though I'm now unable to start GestureSign. When starting I see the GestureSign logo for a moment and then I get the following error message (some parts are in german, if you need a translation just ask):

> Error
> 
> System.Security.Principal.IdentityNotMappedException: Manche oder alle Identitätsverweise konnten nicht übersetzt werden.
> 
>    bei System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
> 
>    bei System.Security.Principal.NTAccount.Translate(Type targetType)
> 
>    bei System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
> 
>    bei System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
> 
>    bei GestureSign.Common.InterProcessCommunication.NamedPipe.RunNamedPipeServer(String pipeName, IMessageProcessor messageProcessor)
> 
>    bei GestureSign.ControlPanel.App.Application_Startup(Object sender, StartupEventArgs e)
> 
> OK   

Please let me know if you need any additional information.
Greeting sonst-was

**Comment by cannibalox** [comment]
5.3.0.0 is broken for me too. 5.2 works fine

> [2017-07-18 12:08:49] System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
   at GestureSign.Common.InterProcessCommunication.NamedPipe.RunNamedPipeServer(String pipeName, IMessageProcessor messageProcessor)
   at GestureSign.ControlPanel.App.Application_Startup(Object sender, StartupEventArgs e)

**Comment by TransposonY** [comment]
Remove PipeAccessRules 7d1802e0 fd296de6
