### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by schaden-freude** [TransposonY/GestureSign#4]
I have set the 2-finger-up gesture to increase the screen brightness by 10%. Every time I do that GestureSign crashes. I am using v0.18.1 with the installation mode.

Here is a log:

02/28/2016 19:27:54
Application: GestureSignDaemon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
Stack:
   at System.Management.ManagementScope.InitializeGuts(System.Object)
   at System.Management.ThreadDispatch.ThreadEntryPointMethodWithParam()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Here is a log from the earlier version, i.e v0.17

02/18/2016 23:33:05
Application: GestureSignDaemon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
Stack:
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr, IntPtr, IntPtr, Int32)
   at System.Windows.Forms.UnsafeNativeMethods.CreateStdAccessibleObject(System.Runtime.InteropServices.HandleRef, Int32, System.Guid ByRef, System.Object ByRef)
   at System.Windows.Forms.AccessibleObject.UseStdAccessibleObjects(IntPtr, Int32)
   at System.Windows.Forms.AccessibleObject.UseStdAccessibleObjects(IntPtr)
   at System.Windows.Forms.Control+ControlAccessibleObject.set_Handle(IntPtr)
   at System.Windows.Forms.Control.OnHandleCreated(System.EventArgs)
   at System.Windows.Forms.Form.OnHandleCreated(System.EventArgs)
   at System.Windows.Forms.Control.WmCreate(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WmCreate(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.IntCreateWindowEx(Int32, System.String, System.String, Int32, Int32, Int32, Int32, Int32, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Object)
   at System.Windows.Forms.UnsafeNativeMethods.IntCreateWindowEx(Int32, System.String, System.String, Int32, Int32, Int32, Int32, Int32, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Object)
   at System.Windows.Forms.UnsafeNativeMethods.CreateWindowEx(Int32, System.String, System.String, Int32, Int32, Int32, Int32, Int32, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Object)
   at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at GestureSign.Daemon.Surface.SurfaceForm.SetHBitmap(IntPtr, System.Drawing.Rectangle, System.Drawing.Point, System.Drawing.Rectangle, Byte)
   at GestureSign.Daemon.Surface.SurfaceForm.SetDiBitmap(GestureSign.Daemon.Surface.DiBitmap, System.Drawing.Rectangle, Byte)
   at GestureSign.Daemon.Surface.SurfaceForm.ClearSurfaces()
   at GestureSign.Daemon.Surface.SurfaceForm.Instance_CaptureStarted(System.Object, GestureSign.Common.Input.PointsCapturedEventArgs)
   at GestureSign.Common.Input.PointsCapturedEventHandler.Invoke(System.Object, GestureSign.Common.Input.PointsCapturedEventArgs)
   at GestureSign.Daemon.Input.TouchCapture.OnCaptureStarted(GestureSign.Common.Input.PointsCapturedEventArgs)
   at GestureSign.Daemon.Input.TouchCapture.TryBeginCapture(System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<Int32,System.Drawing.Point>>)
   at GestureSign.Daemon.Input.TouchCapture.PointEventTranslator_TouchDown(System.Object, GestureSign.Common.Input.PointEventArgs)
   at GestureSign.Daemon.Input.TouchEventTranslator.OnTouchDown(GestureSign.Common.Input.PointEventArgs)
   at GestureSign.Daemon.Input.MessageWindow.ProcessInputCommand(IntPtr)
   at GestureSign.Daemon.Input.MessageWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at GestureSign.Daemon.Program.Main()

I am running Windows 10 (64-bit). Setting that 2-finger-up gesture to "Show Keyboard" action doesn't seem to result in a crash.

**Comment by TransposonY** [comment]
Thanks for the feedback.I received several similar crash reports,the call stack seem to be random,running under Windows 10 64-bit.The strange thing is I have never encountered this problem on my laptop(Windows 10 64-bit).
Running in Compatibility Mode for Windows 8 may help(not verified).
I'm investigating the cause of these crashes, hoping for more information...

**Comment by schaden-freude** [comment]
I tried running it in compatibility mode but that was of no avail. In addition, I tried disabling my antivirus, which again, didn't help.

I would be glad to provide any further information.

**Comment by TransposonY** [comment]
It work fine as 32-bit process
3f1a7bd1d4b88204df6fe4b90836d4ea51bb7b9a

**Comment by schaden-freude** [comment]
Great. It works perfectly fine now. Thanks for the update. :grinning: 

I am not sure if this is the right place for feature requests, but are there any plans to add long press and double tap (multiple taps in general) gestures?

**Comment by TransposonY** [comment]
Nice idea.I will consider implementing these gestures.

**Comment by mikhoul** [comment]
> I am not sure if this is the right place for feature requests, but are there any plans to add long press and double tap (multiple taps in general) gestures?

I agree and second the motion :blush:

**Comment by schaden-freude** [comment]
I think there was an option in the previous releases to set GetsureSign to intercept/override all the touch input when used in installation mode. Now that seems to be possible only by setting it individually per app. The "Intercept Touch Input" option is greyed out when I right click on "All Applications". In a similar fashion, the "Allow Single Stroke" too, is greyed out for all applications. Is this the intended behaviour? If so, is there a reason for that?

PS: The splash is quite nice.

**Comment by TransposonY** [comment]
I think the global "Intercept Touch Input" switch is redundant for the latest version.You can not enable "Intercept Touch Input" or "Allow Single Stroke" feature for "All Applications".It may cause some problems, such as difficulties in touch operation.
